

services:
  fastapi_service:
    build: .
    container_name: fastapi_service
    ports:
      - "2346:8000"
    env_file:
      - .env
    networks:
      - red_postgres

networks:
  red_postgres:
    external: true
